//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_ShopTwo.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Recipe
    {
        public int Id { get; set; }
        public int Item_Id { get; set; }
        public int Recipe_Id { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
